name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file ./Kafka-Subscriber/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/kafka-subscriber:latest
    - name: Build the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kafka-subscriber:latest
