name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file ./Kafka-Subscriber/Dockerfile --tag defyjoy/kafka-subscriber:$(date +%s)
      
    - name: Build the Docker image
      run: docker push defyjoy/kafka-subscriber:$(date +%s)
